"use client";

import { useState } from "react";
import { Download } from "lucide-react";
import type { GeneratedCopy, Product } from "@/lib/products";

interface DownloadBarProps {
  product: Product;
  copyResult: GeneratedCopy;
  imageUrl: string | null;
}

/** Slug a product name into a safe filename fragment. */
function slug(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-");
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoke a tick later so the download has a chance to start.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function buildCampaignText(product: Product, c: GeneratedCopy): string {
  const tt = c.tiktok_script;
  return `MD CREATIVE — ${product.name.toUpperCase()} CAMPAIGN
Generated by MD Creative for mdlondon
---

CAMPAIGN ANGLE
${c.campaignAngle}

CREATIVE DIRECTION
${c.creativeDirection}

INSTAGRAM CAPTION
${c.instagramCaption}

HASHTAGS
${c.hashtags.join(" ")}

PAID AD COPY — SHORT
${c.adCopy[0]}

PAID AD COPY — BENEFIT-LED
${c.adCopy[1]}

PAID AD COPY — STORY
${c.adCopy[2]}

TIKTOK SCRIPT
Hook: ${tt.hook}
Step 1: ${tt.step1}
Step 2: ${tt.step2}
CTA: ${tt.cta}
Audio vibe: ${tt.audio_vibe}

AUDIENCE
${c.audienceTargeting}

PLATFORM
${c.bestPlatform}

CTA
${c.ctaRecommendation}

---
MD Creative — Built by Kautum Krishnan for mdlondon
`;
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`failed to load ${src}`));
    img.src = src;
  });
}

/**
 * Redraw the AD CREATIVE composite (scene + multiply product overlay) onto an
 * offscreen canvas and download it. If either image taints the canvas (CORS),
 * fall back to opening the raw scene URL in a new tab.
 */
async function downloadComposite(
  product: Product,
  imageUrl: string,
): Promise<void> {
  const W = 1024;
  const H = 768;
  try {
    const canvas = document.createElement("canvas");
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("no 2d context");

    const scene = await loadImage(imageUrl);
    // cover-fit the scene
    const scale = Math.max(W / scene.naturalWidth, H / scene.naturalHeight);
    const sw = scene.naturalWidth * scale;
    const sh = scene.naturalHeight * scale;
    ctx.drawImage(scene, (W - sw) / 2, (H - sh) / 2, sw, sh);

    const prod = await loadImage(product.imageUrl);
    const maxW = W * 0.66;
    const maxH = H * 0.6;
    const pScale = Math.min(maxW / prod.naturalWidth, maxH / prod.naturalHeight);
    const pw = prod.naturalWidth * pScale;
    const ph = prod.naturalHeight * pScale;
    ctx.globalCompositeOperation = "multiply";
    ctx.drawImage(prod, (W - pw) / 2, (H - ph) / 2, pw, ph);
    ctx.globalCompositeOperation = "source-over";

    const blob = await new Promise<Blob | null>((resolve) =>
      canvas.toBlob((b) => resolve(b), "image/png"),
    );
    if (!blob) throw new Error("toBlob returned null");
    triggerDownload(blob, `mdcreative-${slug(product.name)}-ad-creative.png`);
  } catch {
    // CORS-tainted canvas or load failure — give the user the raw image.
    window.open(imageUrl, "_blank");
    alert("Save the image from the new tab.");
  }
}

export default function DownloadBar({
  product,
  copyResult,
  imageUrl,
}: DownloadBarProps) {
  const [busy, setBusy] = useState(false);

  const handleDownload = async () => {
    if (busy) return;
    setBusy(true);
    try {
      // 1) Text pack — instant.
      const text = buildCampaignText(product, copyResult);
      triggerDownload(
        new Blob([text], { type: "text/plain" }),
        `mdcreative-${slug(product.name)}-campaign.txt`,
      );
      // 2) Ad-creative PNG — stagger so the browser doesn't drop the 2nd file.
      if (imageUrl) {
        await new Promise((r) => setTimeout(r, 250));
        await downloadComposite(product, imageUrl);
      }
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="w-full">
      <div className="mx-auto max-w-5xl px-6 sm:px-10 py-12">
        <div
          className="flex flex-col gap-5 p-7 sm:flex-row sm:items-center sm:justify-between"
          style={{
            backgroundColor: "var(--bg-surface)",
            border: "1px solid var(--border)",
          }}
        >
          <div className="flex flex-col gap-1.5">
            <span
              className="font-heading uppercase"
              style={{
                color: "var(--text-muted)",
                fontSize: "0.95rem",
                letterSpacing: "0.22em",
              }}
            >
              Campaign Pack
            </span>
            <span
              style={{ color: "rgba(255,255,255,0.4)", fontSize: "0.8rem" }}
            >
              All copy + ad creative, ready to use.
            </span>
          </div>

          <button
            type="button"
            onClick={handleDownload}
            disabled={busy}
            className="flex items-center justify-center gap-2.5 rounded-sm px-7 py-4 text-xs font-medium uppercase tracking-[0.22em] transition-opacity disabled:opacity-60"
            style={{ backgroundColor: "var(--accent)", color: "#fff" }}
          >
            <Download size={15} strokeWidth={2.2} />
            {busy ? "Preparing…" : "Download Pack"}
          </button>
        </div>
      </div>
    </section>
  );
}
