"use client";

import { useState } from "react";
import { Download } from "lucide-react";
import type { GeneratedCopy, Product } from "@/lib/products";
import { FLATLAY_LAYOUTS } from "@/components/ProductOverlays";

interface DownloadBarProps {
  products: Product[];
  copyResult: GeneratedCopy;
  imageUrl: string | null;
}

/** Slug a string into a safe filename fragment. */
function slug(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-");
}

/** Human label for a selection: name / "A + B" / "FULL RANGE". */
function campaignLabel(products: Product[]): string {
  if (products.length === 1) return products[0].name;
  if (products.length >= 6) return "Full Range";
  return products.map((p) => p.name).join(" + ");
}

function fileSlug(products: Product[]): string {
  if (products.length === 1) return slug(products[0].name);
  if (products.length >= 6) return "full-range";
  return "bundle";
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function buildCampaignText(products: Product[], c: GeneratedCopy): string {
  const tt = c.tiktok_script;
  return `MD CREATIVE — ${campaignLabel(products).toUpperCase()} CAMPAIGN
Generated by MD Creative for mdlondon
---

PRODUCTS
${products.map((p) => `- ${p.name} (£${p.price})`).join("\n")}

CAMPAIGN ANGLE
${c.campaignAngle}

CREATIVE DIRECTION
${c.creativeDirection}

INSTAGRAM CAPTION
${c.instagramCaption}

HASHTAGS
${c.hashtags.join(" ")}

PAID AD COPY — SHORT
${c.adCopy[0]}

PAID AD COPY — BENEFIT-LED
${c.adCopy[1]}

PAID AD COPY — STORY
${c.adCopy[2]}

TIKTOK SCRIPT
Hook: ${tt.hook}
Step 1: ${tt.step1}
Step 2: ${tt.step2}
CTA: ${tt.cta}
Audio vibe: ${tt.audio_vibe}

AUDIENCE
${c.audienceTargeting}

PLATFORM
${c.bestPlatform}

CTA
${c.ctaRecommendation}

---
MD Creative — Built by Kautum Krishnan for mdlondon
`;
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`failed to load ${src}`));
    img.src = src;
  });
}

/** Draw one product onto the canvas via multiply at a flat-lay position. */
function drawProductMultiply(
  ctx: CanvasRenderingContext2D,
  img: HTMLImageElement,
  W: number,
  H: number,
  pos: { left: number; top: number; width: number; rotate: number },
) {
  let pw = (pos.width / 100) * W;
  let ph = (pw * img.naturalHeight) / img.naturalWidth;
  const maxH = 0.72 * H;
  if (ph > maxH) {
    ph = maxH;
    pw = (ph * img.naturalWidth) / img.naturalHeight;
  }
  ctx.save();
  ctx.translate((pos.left / 100) * W, (pos.top / 100) * H);
  ctx.rotate((pos.rotate * Math.PI) / 180);
  ctx.drawImage(img, -pw / 2, -ph / 2, pw, ph);
  ctx.restore();
}

/**
 * Redraw the AD CREATIVE composite onto an offscreen canvas, matching whatever
 * tier was shown on screen: hero overlay (1), flat-lay (2-4), or pure scene
 * (5+). On CORS taint / load failure, fall back to opening the raw scene URL.
 */
async function downloadComposite(
  products: Product[],
  imageUrl: string,
): Promise<void> {
  const W = 1024;
  const H = 768;
  try {
    const canvas = document.createElement("canvas");
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("no 2d context");

    const scene = await loadImage(imageUrl);
    const scale = Math.max(W / scene.naturalWidth, H / scene.naturalHeight);
    const sw = scene.naturalWidth * scale;
    const sh = scene.naturalHeight * scale;
    ctx.drawImage(scene, (W - sw) / 2, (H - sh) / 2, sw, sh);

    const n = products.length;
    if (n >= 1 && n <= 4) {
      ctx.globalCompositeOperation = "multiply";
      if (n === 1) {
        const prod = await loadImage(products[0].imageUrl);
        const maxW = W * 0.66;
        const maxH = H * 0.6;
        const ps = Math.min(
          maxW / prod.naturalWidth,
          maxH / prod.naturalHeight,
        );
        const pw = prod.naturalWidth * ps;
        const ph = prod.naturalHeight * ps;
        ctx.drawImage(prod, (W - pw) / 2, (H - ph) / 2, pw, ph);
      } else {
        const layout = FLATLAY_LAYOUTS[n] ?? [];
        // Load all first so paint order matches the layout (back → front).
        const imgs = await Promise.all(
          products.map((p) => loadImage(p.imageUrl)),
        );
        imgs.forEach((img, i) => {
          if (layout[i]) drawProductMultiply(ctx, img, W, H, layout[i]);
        });
      }
      ctx.globalCompositeOperation = "source-over";
    }
    // n >= 5: scene only, no overlay (matches Tier 3 on screen).

    const blob = await new Promise<Blob | null>((resolve) =>
      canvas.toBlob((b) => resolve(b), "image/png"),
    );
    if (!blob) throw new Error("toBlob returned null");
    triggerDownload(blob, `mdcreative-${fileSlug(products)}-ad-creative.png`);
  } catch {
    window.open(imageUrl, "_blank");
    alert("Save the image from the new tab.");
  }
}

export default function DownloadBar({
  products,
  copyResult,
  imageUrl,
}: DownloadBarProps) {
  const [busy, setBusy] = useState(false);

  const handleDownload = async () => {
    if (busy) return;
    setBusy(true);
    try {
      const text = buildCampaignText(products, copyResult);
      triggerDownload(
        new Blob([text], { type: "text/plain" }),
        `mdcreative-${fileSlug(products)}-campaign.txt`,
      );
      if (imageUrl) {
        await new Promise((r) => setTimeout(r, 250));
        await downloadComposite(products, imageUrl);
      }
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="w-full">
      <div className="mx-auto max-w-5xl px-6 sm:px-10 py-12">
        <div
          className="flex flex-col gap-5 p-7 sm:flex-row sm:items-center sm:justify-between"
          style={{
            backgroundColor: "var(--bg-surface)",
            border: "1px solid var(--border)",
          }}
        >
          <div className="flex flex-col gap-1.5">
            <span
              className="font-heading uppercase"
              style={{
                color: "var(--text-muted)",
                fontSize: "0.95rem",
                letterSpacing: "0.22em",
              }}
            >
              Campaign Pack
            </span>
            <span
              style={{ color: "rgba(255,255,255,0.4)", fontSize: "0.8rem" }}
            >
              All copy + ad creative, ready to use.
            </span>
          </div>

          <button
            type="button"
            onClick={handleDownload}
            disabled={busy}
            className="flex items-center justify-center gap-2.5 rounded-sm px-7 py-4 text-xs font-medium uppercase tracking-[0.22em] transition-opacity disabled:opacity-60"
            style={{ backgroundColor: "var(--accent)", color: "#fff" }}
          >
            <Download size={15} strokeWidth={2.2} />
            {busy ? "Preparing…" : "Download Pack"}
          </button>
        </div>
      </div>
    </section>
  );
}
