"use client";

import { useState } from "react";
import { Download } from "lucide-react";
import type { GeneratedCopy, Product } from "@/lib/products";
import {
  getCompositeLayout,
  BASE_MAX_HEIGHT,
} from "@/components/ProductOverlays";
import { getProductCutout } from "@/lib/cutout";

interface DownloadBarProps {
  products: Product[];
  copyResult: GeneratedCopy;
  imageUrl: string | null;
}

/** Slug a string into a safe filename fragment. */
function slug(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-");
}

/** Human label for a selection: name / "A + B" / "FULL RANGE". */
function campaignLabel(products: Product[]): string {
  if (products.length === 1) return products[0].name;
  if (products.length >= 6) return "Full Range";
  return products.map((p) => p.name).join(" + ");
}

function fileSlug(products: Product[]): string {
  if (products.length === 1) return slug(products[0].name);
  if (products.length >= 6) return "full-range";
  return "bundle";
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function buildCampaignText(products: Product[], c: GeneratedCopy): string {
  const tt = c.tiktok_script;
  return `MD CREATIVE — ${campaignLabel(products).toUpperCase()} CAMPAIGN
Generated by MD Creative for mdlondon
---

PRODUCTS
${products.map((p) => `- ${p.name} (£${p.price})`).join("\n")}

CAMPAIGN ANGLE
${c.campaignAngle}

CREATIVE DIRECTION
${c.creativeDirection}

INSTAGRAM CAPTION
${c.instagramCaption}

HASHTAGS
${c.hashtags.join(" ")}

PAID AD COPY — SHORT
${c.adCopy[0]}

PAID AD COPY — BENEFIT-LED
${c.adCopy[1]}

PAID AD COPY — STORY
${c.adCopy[2]}

TIKTOK SCRIPT
Hook: ${tt.hook}
Step 1: ${tt.step1}
Step 2: ${tt.step2}
CTA: ${tt.cta}
Audio vibe: ${tt.audio_vibe}

AUDIENCE
${c.audienceTargeting}

PLATFORM
${c.bestPlatform}

CTA
${c.ctaRecommendation}

---
MD Creative — Built by Kautum Krishnan for mdlondon
`;
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`failed to load ${src}`));
    img.src = src;
  });
}

/** Draw a soft elliptical contact shadow at a product's base on the canvas. */
function drawContactShadow(
  ctx: CanvasRenderingContext2D,
  cx: number,
  baseY: number,
  drawW: number,
  drawH: number,
  footprint: number,
  opacity: number,
) {
  const rx = Math.max(drawW * footprint * 0.48, drawW * 0.1);
  const ry = drawH * 0.065;
  ctx.save();
  ctx.translate(cx, baseY + ry * 0.5);
  ctx.scale(1, ry / rx); // squash the circular gradient into an ellipse
  const g = ctx.createRadialGradient(0, 0, 0, 0, 0, rx);
  g.addColorStop(0, `rgba(0,0,0,${opacity})`);
  g.addColorStop(0.7, "rgba(0,0,0,0)");
  g.addColorStop(1, "rgba(0,0,0,0)");
  ctx.fillStyle = g;
  ctx.beginPath();
  ctx.arc(0, 0, rx, 0, Math.PI * 2);
  ctx.fill();
  ctx.restore();
}

/**
 * Redraw the AD CREATIVE composite onto an offscreen canvas, matching what was
 * shown on screen: the SAME cutout system, real-scale layout and contact
 * shadows (lib/cutout + ProductOverlays.getCompositeLayout), not the old
 * multiply blend. Tiers: hero (1), flat-lay (2-4), pure scene (5+). Cutouts are
 * same-origin data URLs so they never taint the canvas; only the cross-origin
 * scene can — on taint / load failure we fall back to opening the raw scene.
 */
async function downloadComposite(
  products: Product[],
  imageUrl: string,
): Promise<void> {
  const W = 1024;
  const H = 768;
  try {
    const canvas = document.createElement("canvas");
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("no 2d context");

    const scene = await loadImage(imageUrl);
    const scale = Math.max(W / scene.naturalWidth, H / scene.naturalHeight);
    const sw = scene.naturalWidth * scale;
    const sh = scene.naturalHeight * scale;
    ctx.drawImage(scene, (W - sw) / 2, (H - sh) / 2, sw, sh);

    // Tier 1-4: composite products. 5+: scene only (matches Tier 3 on screen).
    const slots = getCompositeLayout(products); // [] for 0 or 5+
    // Resolve cutouts up front, in slot order (back → front), so the canvas
    // paint order matches the on-screen DOM order.
    const cutouts = await Promise.all(
      slots.map((s) => getProductCutout(s.product.imageUrl)),
    );

    for (let i = 0; i < slots.length; i++) {
      const slot = slots[i];
      const cut = cutouts[i];
      const cx = (slot.left / 100) * W;
      const cy = (slot.top / 100) * H;
      const drawH = (slot.heightPct / 100) * H;

      if (cut) {
        const img = await loadImage(cut.url);
        const drawW = drawH * (img.naturalWidth / img.naturalHeight);
        const prominence = Math.min(1, slot.heightPct / BASE_MAX_HEIGHT);
        const opacity = 0.22 + 0.24 * prominence;
        // Contact shadow first, then the product on top.
        drawContactShadow(
          ctx,
          cx,
          cy + drawH / 2,
          drawW,
          drawH,
          cut.footprint,
          opacity,
        );
        ctx.save();
        ctx.translate(cx, cy);
        ctx.rotate((slot.rotate * Math.PI) / 180);
        ctx.drawImage(img, -drawW / 2, -drawH / 2, drawW, drawH);
        ctx.restore();
      } else {
        // Cutout failed — fall back to the raw image via multiply (matches the
        // on-screen fallback) so the product still appears.
        const img = await loadImage(slot.product.imageUrl);
        const drawW = drawH * (img.naturalWidth / img.naturalHeight);
        ctx.save();
        ctx.globalCompositeOperation = "multiply";
        ctx.translate(cx, cy);
        ctx.rotate((slot.rotate * Math.PI) / 180);
        ctx.drawImage(img, -drawW / 2, -drawH / 2, drawW, drawH);
        ctx.restore();
      }
    }

    const blob = await new Promise<Blob | null>((resolve) =>
      canvas.toBlob((b) => resolve(b), "image/png"),
    );
    if (!blob) throw new Error("toBlob returned null");
    triggerDownload(blob, `mdcreative-${fileSlug(products)}-ad-creative.png`);
  } catch {
    window.open(imageUrl, "_blank");
    alert("Save the image from the new tab.");
  }
}

export default function DownloadBar({
  products,
  copyResult,
  imageUrl,
}: DownloadBarProps) {
  const [busy, setBusy] = useState(false);

  const handleDownload = async () => {
    if (busy) return;
    setBusy(true);
    try {
      const text = buildCampaignText(products, copyResult);
      triggerDownload(
        new Blob([text], { type: "text/plain" }),
        `mdcreative-${fileSlug(products)}-campaign.txt`,
      );
      if (imageUrl) {
        await new Promise((r) => setTimeout(r, 250));
        await downloadComposite(products, imageUrl);
      }
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="w-full">
      <div className="mx-auto max-w-5xl px-6 sm:px-10 py-12">
        <div
          className="flex flex-col gap-5 p-7 sm:flex-row sm:items-center sm:justify-between"
          style={{
            backgroundColor: "var(--bg-surface)",
            border: "1px solid var(--border)",
          }}
        >
          <div className="flex flex-col gap-1.5">
            <span
              className="font-heading uppercase"
              style={{
                color: "var(--text-muted)",
                fontSize: "0.95rem",
                letterSpacing: "0.22em",
              }}
            >
              Campaign Pack
            </span>
            <span
              style={{ color: "var(--text-muted)", fontSize: "0.8rem" }}
            >
              All copy + ad creative, ready to use.
            </span>
          </div>

          <button
            type="button"
            onClick={handleDownload}
            disabled={busy}
            className="flex items-center justify-center gap-2.5 rounded-sm px-7 py-4 text-xs font-medium uppercase tracking-[0.22em] transition-opacity disabled:opacity-60"
            style={{ backgroundColor: "var(--accent)", color: "#fff" }}
          >
            <Download size={15} strokeWidth={2.2} />
            {busy ? "Preparing…" : "Download Pack"}
          </button>
        </div>
      </div>
    </section>
  );
}
